basePath: /
definitions:
  response.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: ashinchen@tencent.com
    name: API Support
    url: http://km.oa.com/user/ashinchen
  description: response current api version
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Gin-Skeleton Web API
  version: 0.0.1
paths:
  /x/ping:
    get:
      description: response current api version
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
            type: object
      summary: Ping for server is living
      tags:
      - x
swagger: "2.0"
