language: go

go:
  - "1.11.x"
  - "1.12.x"
  - "1.13.x"
  - master

go_import_path: pink-lady

env:
  - GO111MODULE=on

script:
  - cp app/config.toml.example app/config.toml
  - go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
