language: go

go:
  - "1.11.x"
  - "1.12.x"
  - "1.13.x"
  - "1.14.x"
  - master

go_import_path: github.com/axiaoxin-com/pink-lady

env:
  - GO111MODULE=on

services:
  - mysql
  - postgresql
  - redis-server

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
