language: go

go:
  - "1.10.x"
  - "1.11.x"
  - master

go_import_path: github.com/axiaoxin/pink-lady

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
