server:
    mode: debug
    bind: :8080
log:
    out: stdout
    level: debug
    formatter: text
database:
    engine: sqlite3
    address: ''
    name: /tmp/gin-skeleton.db
    username: ''
    password: ''
