server:
    mode: debug
    bind: :8080
log:
    level: debug
    formatter: text
database:
    engine: sqlite3
    address: ''
    name: /tmp/gin-skeleton.db
    username: ''
    password: ''
redis:
    mode: single-instance
    address: localhost:6379
    password: ''
    db: 0
    master: ''
sentry:
    dsn: ''
    onlycrashes: false
