server:
    mode: debug
    bind: :8080
log:
    level: debug
    formatter: text
database:
    engine: sqlite3
    address: ''
    name: /tmp/gin-skeleton.db
    username: ''
    password: ''
    max_idle_conns: 2
    max_open_conns: 0
    conn_max_life_minutes: 60
    log_mode: true
redis:
    mode: single-instance
    address: localhost:6379
    password: ''
    db: 0
    master: ''
sentry:
    dsn: ''
    onlycrashes: false
