#############################
#                           #
# viper web server 配置文件 #
#                           #
#############################


########## 环境配置
env = "dev"

########## server 相关配置
[server]
# server 运行地址，支持 HTTP 端口 ":port" 或 UNIX Socket "unix:/file"
addr = ":4869"
# gin mode ，可选值： debug 、 test 、 release
mode = "debug"
# 开启 pprof
pprof = true
# 服务器从 accept 到读取 body 的超时时间（秒）
read_timeout = 5
# 服务器从 accept 到写 response 的超时时间（秒）
write_timeout = 5

########## 日志相关配置
[logging]
# 日志级别，可选值： debug info warn error dpanic panic fatal
level = "debug"
# 日志格式，可选值： json console
format = "json"
# 日志输出路径
output_paths = ["stdout"]
# 是否关闭打印 caller 字段
disable_caller = false
# 是否关闭打印 stacktrace 字段
disable_stacktrace = true
## 动态修改日志级别 http 服务配置
[logging.atomic_level_server]
# http 服务端口
addr = ":4870"
# 接口 url path
path = ""
## 访问日志相关配置
[logging.access_logger]
# 关闭打印 details 字段
disable_details = false
# 开启 details 字段时，打印 context 中的 keys 信息
details_with_context_keys = false
# 开启 details 字段时，打印请求 body 和 响应 body。慎用！影响性能严重，仅调试时使用
details_with_body = false
# 不打印日志的 path
skip_paths = [
    "/x/apidocs/doc.json",
    "/x/apidocs/swagger-ui-bundle.js",
    "/x/apidocs/swagger-ui-standalone-preset.js",
    "/x/apidocs/swagger-ui.css",
]

########## sentry 相关配置
[sentry]
# sentry dsn
dsn = ""
debug = true

########## apidocs 相关配置
[apidocs]
# 文档标题
title = "pink-lady swagger apidocs"
# 文档描述
desc = "Using pink-lady to develop gin app on fly."
# 请求地址，端口要和 server.addr 一致，浏览器访问时需要区分 127.0.0.1 和 localhost
host = "localhost:4869"
# 请求地址的 basepath
basepath = "/"
# 支持的请求 schemes
schemes = ["http"]

########## basic auth 相关配置
[basic_auth]
# 登录用户名
username = "admin"
# 登录密码
password = "admin"

########## MySQL 相关配置
# mysql 按不同环境可以添加多个配置
# 本地配置
[mysql.localhost]
host = "localhost"
port = 3306
username = "root"
password = "roooooot"
dbname = "test"
log_mode = false
max_idle_conns = 20
max_open_conns = 20
conn_max_life_minutes = 10
conn_timeout = 3
read_timeout = 5
write_timeout = 5
# 其他环境
[mysql.other]

########## SQLite3 相关配置
[sqlite3.dev]
dbname = "sqlite3.dev.db"
log_mode = false

########## Postgres 相关配置
[postgres.localhost]
host = "localhost"
port = 5432
username = "root"
password = "roooooot"
dbname = "test"
log_mode = false
max_idle_conns = 20
max_open_conns = 20
conn_max_life_minutes = 10
disable_ssl = true

########## MsSQL 相关配置
[mssql.localhost]
host = "localhost"
port = 1433
username = "root"
password = "roooooot"
dbname = "test"
log_mode = false
max_idle_conns = 20
max_open_conns = 20
conn_max_life_minutes = 10

########## Redis 相关配置
# redis 按不同环境可以添加多个配置
[redis]
    # 本地配置
    [redis.localhost]
        mode = "normal"
        address = "localhost:6379"
        password = ""
        dbindex = 0
        master = ""
    [redis.other]
